apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-orders:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: order_user
  SPRING_DATASOURCE_PASSWORD: order_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  db-password: order_pass

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082