apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-products:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: product_user

---
apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
stringData:
  db-password: product_pass

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 8081
      targetPort: 8081